version: "3.7"
services:
  app:
    build:
      args:
        user: sandro
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: testesandro
    container_name: testesandro-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./teste:/var/www
    networks:
      - testesandro

  db:
    image: mysql:5.7
    container_name: testesandro-db
    restart: always
    ports:
        - '3306:3306'
    environment:
      - MYSQL_DATABASE=testesandro
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - testesandro

  nginx:
    image: nginx:alpine
    container_name: testesandro-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./teste:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - db
    links:
      - db
    networks:
      - testesandro

networks:
  testesandro:
    driver: bridge